### ISSUE TITLE
TryGet current on cursor throws exception when no current record

### ISSUE THREAD

**Issue by aliostad** [Spreads/Spreads.LMDB#27]
Hi,

I am deleting records and found out if I delete the last record, I get an exception calling this:

``` csharp 
c.TryGet(ref keydb, ref valdb, CursorGetOption.GetCurrent);
```
The exception is:

```
andling exception: Spreads.LMDB.LMDBException: Invalid argument
[xUnit.net 00:00:05.4860040]            at Spreads.LMDB.Interop.NativeMethods.ThrowLMDBEx(Int32 res) in C:\MD\Dev\Spreads\Spreads.LMDB\src\Spreads.LMDB\Interop\NativeMethods.cs:line 127
[xUnit.net 00:00:05.4862130]            at Spreads.LMDB.Cursor.TryGet(DirectBuffer& key, DirectBuffer& value, CursorGetOption operation) in C:\MD\Dev\Spreads\Spreads.LMDB\src\Spreads.LMDB\Cursor.cs:line 66
[xUnit.net 00:00:05.4863290]            at
```

Is this expected? `TryGet` really should not get an exception since I am not doing anything special.

**Comment by buybackoff** [comment]
`CursorGetOption.GetCurrent` does not try to find anything but reads current cursor position. Since there are no current value after deletion then the call is invalid. The question is should we just try/catch this since the method is `Try...`. Do you have an isolated repro?

**Comment by buybackoff** [comment]
The current logic returns false only on `MDB_NOTFOUND`, as an alternative to .NET's `KeyNotFoundException`. I believe invalid calls should still throw, otherwise debugging would be terrible and you could spend hours trying to find what doesn't work. LMDB API is quite fragile on misuse and quite opaque on *what exactly* is wrong, so I would propose to wrap your call into `try/catch` yourself if that just simplifies things. But getting current value when it no longer exists is not the same as trying to find a key that is not present, but rather a .NET's `InvalidOperationException`.

![image](https://user-images.githubusercontent.com/489852/56156501-1448f600-5fc6-11e9-871a-901fb6c522ea.png)

**Comment by aliostad** [comment]
The problem is AFAICR the cursor in LMDB provides whether currently sitting at a record but this is not exposed here - I am speculating here please correct me if I am wrong. Try/Catch is not the right solution, we should not catch exception to find out whether I am currently at a record or not. Essentially, I have deleted records one by one and turns out no record left - a cursor should have a property to tell me something like EOF, etc.

**Comment by buybackoff** [comment]
> cursor in LMDB provides whether currently sitting at a record

What native LMDB API provides this?

You said that you've deleted all records but then trying to get the current one, which does not exist anymore. Maybe I do not follow and `DeleteUpToValue` is not a part of this lib or LMDB API.

**Comment by aliostad** [comment]
Sorry I was about to post `DeleteUpToValue`. Posted now. Happy to present a repro which has no custom code - if makes it easier.

**Comment by buybackoff** [comment]
OK, will look into it.

But do you agree in principle that you cannot "get current" after you've deleted everything? Or your insist that we should just return false in this case, like .NET Dictionary TryGetValue?

**Comment by buybackoff** [comment]
> Happy to present a repro which has no custom code - if makes it easier.

I believe a "dream pull request" is a unit test that fails so that I could fix it ASAP.

**Comment by aliostad** [comment]
> But do you agree in principle that you cannot "get current" after you've deleted everything?

If I were designing an API from scratch, I would never throw an exception from a method with TryXXX name. But you are exposing another API hence you have got to stay faithful to the LMDB behaviour, hence if it throws exception, you need to throw. The only thing is, I need to have a way of checking without a try/catch.

I will send a PR for a unit test.

**Comment by aliostad** [comment]
why .NET Core 3?? It is barely out.

**Comment by buybackoff** [comment]
> why .NET Core 3?? It is barely out.

It's the future and I actually use SIMD intrinsics already beyond Vectors, e.g. CRC32c. Also Blake2b much faster than native libsodium for small payloads due to saving on P/Invoke call.

The lib itself is actually netstandard, so test proj could target anything..

**Comment by buybackoff** [comment]
See the commit https://github.com/Spreads/Spreads.LMDB/commit/002e9b0d4a5e632c6e2a8330b36e4b19d8b01639 and comments in the test. 

You probably wanted to use `GetBothRange` since `GetCurrent` does not try to position a cursor at the provided values, but tries to return the current position that depends on previous successful moves. It's a misuse trying to get current after deleting the last dupsorted value, because main key no longer exists after that.  `GetCurrent`  is useful when you first call `TryGet` with `FirstDuplicate`/`LastDuplicate`/`NextDuplicate`/`PreviousDuplicate`, when the input value of the second argument is not used. However those relative moves must already update the `byref` second argument after successful move, so I don't know when this option is actually useful. I do not use it in https://github.com/DataSpreads/DataSpreads, which I published recently and which heavily relies on this library (and the reason for it's existence).

**Comment by aliostad** [comment]
OK so will use `GetBothRange`. Thanks a lot.
